version: "3.6"

volumes:
  keys:
  cargo-registry:
  cargo-git:
  cargo-target:
services:
  validator-0:
    image: sawtooth-pbft-test:latest
    container_name: validator-0
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8800
      - 5005
    volumes:
      - ./settings:/settings
      - keys:/shared_keys
    working_dir: /root
    command: "bash -c \"\
        sawadm keygen validator-1 && \
        sawadm keygen validator-2 && \
        sawadm keygen validator-3 && \
        sawadm keygen && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm.name=pbft \
          sawtooth.consensus.algorithm.version=1.0 \
          sawtooth.consensus.pbft.members=\\['\\\"'$$(cat /etc/sawtooth/keys/validator.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-1.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-2.pub)'\\\"','\\\"'$$(cat /etc/sawtooth/keys/validator-3.pub)'\\\"'\\] \
          -o config.batch && \
        sawadm genesis \
          config-genesis.batch config.batch && \
        mv /etc/sawtooth/keys/validator-* /shared_keys && \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
    \""

    stop_signal: SIGKILL
  validator-1:
    image: sawtooth-pbft-test:latest
    container_name: validator-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
      - 5005
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-1.pub ]; then mv /shared_keys/validator-1.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-1.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-1:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
    \""
    stop_signal: SIGKILL
  validator-2:
    image: sawtooth-pbft-test:latest
    container_name: validator-2
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
      - 5005
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-2.pub ]; then mv /shared_keys/validator-2.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-2.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-2:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
    \""
    stop_signal: SIGKILL
  validator-3:
    image: sawtooth-pbft-test:latest
    container_name: validator-3
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
      - 5005
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-3.pub ]; then mv /shared_keys/validator-3.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-3.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-3:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800,tcp://validator-1:8800,tcp://validator-2:8800
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
    \""
    stop_signal: SIGKILL
  pbft-0:
    image: sawtooth-pbft-engine-local:latest
    container_name: sawtooth-pbft-engine-default-0
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ..:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-0:5050 -vv
    stop_signal: SIGKILL
  pbft-1:
    image: sawtooth-pbft-engine-local:latest
    container_name: sawtooth-pbft-engine-default-1
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ..:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-1:5050 -vv
    stop_signal: SIGKILL
  pbft-2:
    image: sawtooth-pbft-engine-local:latest
    container_name: sawtooth-pbft-engine-default-2
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ..:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-2:5050 -vv
    stop_signal: SIGKILL
  pbft-3:
    image: sawtooth-pbft-engine-local:latest
    container_name: sawtooth-pbft-engine-default-3
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ..:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-3:5050 -vv
    stop_signal: SIGKILL
  rest-api-0:
    image: sawtooth-pbft-test:latest
    container_name: rest-api-0
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-0:4004 --bind rest-api-0:8008
    depends_on:
      - validator-0
    stop_signal: SIGKILL
  rest-api-1:
    image: sawtooth-pbft-test:latest
    container_name: rest-api-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL
  rest-api-2:
    image: sawtooth-pbft-test:latest
    container_name: rest-api-2
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-2:4004 --bind rest-api-2:8008
    stop_signal: SIGKILL
  rest-api-3:
    image: sawtooth-pbft-test:latest
    container_name: rest-api-3
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-3:4004 --bind rest-api-3:8008
    stop_signal: SIGKILL
  shell-0:
    image: hyperledger/sawtooth-all:1.0
    container_name: shell-0
    depends_on:
      - rest-api-0
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  settings-tp-0:
    image: sawtooth-pbft-test:latest
    container_name: settings-tp-0
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004 -v
    stop_signal: SIGKILL
  settings-tp-1:
    image: sawtooth-pbft-test:latest
    container_name: settings-tp-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004 -v
    stop_signal: SIGKILL
  settings-tp-2:
    image: sawtooth-pbft-test:latest
    container_name: settings-tp-2
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL
  settings-tp-3:
    image: sawtooth-pbft-test:latest
    container_name: settings-tp-3
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    stop_signal: SIGKILL
