version: "3.6"

volumes:
  keys:
  cargo-registry:
  cargo-git:
  cargo-target:
services:
  validator-1:
    image: sawtooth-pbft-test:latest
    container_name: sawtooth-validator-default-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    volumes:
      - keys:/shared_keys
    expose:
      - 4004
      - 8800
    command: "bash -c \"\
        while true; do if [ -e /shared_keys/validator-1.pub ]; then mv /shared_keys/validator-1.priv /etc/sawtooth/keys/validator.priv && mv /shared_keys/validator-1.pub /etc/sawtooth/keys/validator.pub; break; fi; sleep 0.5; done; \
        echo $$(cat /etc/sawtooth/keys/validator.pub); \
        sawtooth-validator \
            --endpoint tcp://validator-1:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --peers tcp://validator-0:8800
            --scheduler parallel \
            --maximum-peer-connectivity 3 \
    \""
    stop_signal: SIGKILL
    networks:
      - sawtooth



  pbft-1:
    image: sawtooth-pbft-engine-local:latest
    container_name: sawtooth-pbft-engine-default-1
    build:
      context: .
      dockerfile: ../Dockerfile
    volumes:
      - ..:/project/sawtooth-pbft
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
    working_dir: /project/sawtooth-pbft/
    command: ./target/debug/pbft-engine --connect tcp://validator-1:5050 -vv
    stop_signal: SIGKILL
    networks:
      - sawtooth

  rest-api-1:
    image: sawtooth-pbft-test:latest
    container_name: rest-api-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
      - 8008
    command: sawtooth-rest-api --connect tcp://validator-1:4004 --bind rest-api-1:8008
    stop_signal: SIGKILL
    networks:
      - sawtooth
  settings-tp-1:
    image: sawtooth-pbft-test:latest
    container_name: settings-tp-1
    build:
      context: .
      dockerfile: sawtooth-pbft-test.dockerfile
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004 -v
    stop_signal: SIGKILL
    networks:
      - sawtooth
networks:
  sawtooth:
    external:
      name: sawtooth