bind = [
  "network:tcp://eth0:8800",
  "component:tcp://eth0:4004",
  "consensus:tcp://eth0:5050"
]

peering = "static"

endpoint = "tcp://validator-2:8800"

peers = ["tcp://validator-1:8800","tcp://validator-0:8800","tcp://validator-3:8800"]


scheduler = "parallel"

minimum_peer_connectivity = 1
